sudo: required
services:
  - docker
before_install:
  - docker build -t soban252/travis:v1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push soban252/travis:v1.0
notifications:
  email:
    recipients:
      - sobankhan252@gmail.com
    on_success: always
    on_failure: always
